/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSorteosRouteImport } from './routes/_app/sorteos'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPanelRouteImport } from './routes/_app/panel'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppIntegrantesIndexRouteImport } from './routes/_app/integrantes.index'
import { Route as AppEventosIndexRouteImport } from './routes/_app/eventos.index'
import { Route as AppIntegrantesIdRouteImport } from './routes/_app/integrantes.$id'
import { Route as AppGruposIdRouteImport } from './routes/_app/grupos.$id'
import { Route as AppEventosTypeRouteImport } from './routes/_app/eventos.$type'
import { Route as AppAdminGrupoIdRouteImport } from './routes/_app/admin.grupo.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSorteosRoute = AppSorteosRouteImport.update({
  id: '/sorteos',
  path: '/sorteos',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPanelRoute = AppPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrantesIndexRoute = AppIntegrantesIndexRouteImport.update({
  id: '/integrantes/',
  path: '/integrantes/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosIndexRoute = AppEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrantesIdRoute = AppIntegrantesIdRouteImport.update({
  id: '/integrantes/$id',
  path: '/integrantes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposIdRoute = AppGruposIdRouteImport.update({
  id: '/grupos/$id',
  path: '/grupos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosTypeRoute = AppEventosTypeRouteImport.update({
  id: '/eventos/$type',
  path: '/eventos/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGrupoIdRoute = AppAdminGrupoIdRouteImport.update({
  id: '/grupo/$id',
  path: '/grupo/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/registro': typeof RegistroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/panel': typeof AppPanelRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/sorteos': typeof AppSorteosRoute
  '/eventos/$type': typeof AppEventosTypeRoute
  '/grupos/$id': typeof AppGruposIdRoute
  '/integrantes/$id': typeof AppIntegrantesIdRoute
  '/eventos/': typeof AppEventosIndexRoute
  '/integrantes/': typeof AppIntegrantesIndexRoute
  '/admin/grupo/$id': typeof AppAdminGrupoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/registro': typeof RegistroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/panel': typeof AppPanelRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/sorteos': typeof AppSorteosRoute
  '/eventos/$type': typeof AppEventosTypeRoute
  '/grupos/$id': typeof AppGruposIdRoute
  '/integrantes/$id': typeof AppIntegrantesIdRoute
  '/eventos': typeof AppEventosIndexRoute
  '/integrantes': typeof AppIntegrantesIndexRoute
  '/admin/grupo/$id': typeof AppAdminGrupoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/registro': typeof RegistroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/panel': typeof AppPanelRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/sorteos': typeof AppSorteosRoute
  '/_app/eventos/$type': typeof AppEventosTypeRoute
  '/_app/grupos/$id': typeof AppGruposIdRoute
  '/_app/integrantes/$id': typeof AppIntegrantesIdRoute
  '/_app/eventos/': typeof AppEventosIndexRoute
  '/_app/integrantes/': typeof AppIntegrantesIndexRoute
  '/_app/admin/grupo/$id': typeof AppAdminGrupoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/registro'
    | '/sitemap.xml'
    | '/admin'
    | '/panel'
    | '/perfil'
    | '/ranking'
    | '/sorteos'
    | '/eventos/$type'
    | '/grupos/$id'
    | '/integrantes/$id'
    | '/eventos/'
    | '/integrantes/'
    | '/admin/grupo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/registro'
    | '/sitemap.xml'
    | '/admin'
    | '/panel'
    | '/perfil'
    | '/ranking'
    | '/sorteos'
    | '/eventos/$type'
    | '/grupos/$id'
    | '/integrantes/$id'
    | '/eventos'
    | '/integrantes'
    | '/admin/grupo/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/registro'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/panel'
    | '/_app/perfil'
    | '/_app/ranking'
    | '/_app/sorteos'
    | '/_app/eventos/$type'
    | '/_app/grupos/$id'
    | '/_app/integrantes/$id'
    | '/_app/eventos/'
    | '/_app/integrantes/'
    | '/_app/admin/grupo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegistroRoute: typeof RegistroRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sorteos': {
      id: '/_app/sorteos'
      path: '/sorteos'
      fullPath: '/sorteos'
      preLoaderRoute: typeof AppSorteosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrantes/': {
      id: '/_app/integrantes/'
      path: '/integrantes'
      fullPath: '/integrantes/'
      preLoaderRoute: typeof AppIntegrantesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos/': {
      id: '/_app/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AppEventosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrantes/$id': {
      id: '/_app/integrantes/$id'
      path: '/integrantes/$id'
      fullPath: '/integrantes/$id'
      preLoaderRoute: typeof AppIntegrantesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos/$id': {
      id: '/_app/grupos/$id'
      path: '/grupos/$id'
      fullPath: '/grupos/$id'
      preLoaderRoute: typeof AppGruposIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos/$type': {
      id: '/_app/eventos/$type'
      path: '/eventos/$type'
      fullPath: '/eventos/$type'
      preLoaderRoute: typeof AppEventosTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/grupo/$id': {
      id: '/_app/admin/grupo/$id'
      path: '/grupo/$id'
      fullPath: '/admin/grupo/$id'
      preLoaderRoute: typeof AppAdminGrupoIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminGrupoIdRoute: typeof AppAdminGrupoIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminGrupoIdRoute: AppAdminGrupoIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppPanelRoute: typeof AppPanelRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppSorteosRoute: typeof AppSorteosRoute
  AppEventosTypeRoute: typeof AppEventosTypeRoute
  AppGruposIdRoute: typeof AppGruposIdRoute
  AppIntegrantesIdRoute: typeof AppIntegrantesIdRoute
  AppEventosIndexRoute: typeof AppEventosIndexRoute
  AppIntegrantesIndexRoute: typeof AppIntegrantesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppPanelRoute: AppPanelRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppSorteosRoute: AppSorteosRoute,
  AppEventosTypeRoute: AppEventosTypeRoute,
  AppGruposIdRoute: AppGruposIdRoute,
  AppIntegrantesIdRoute: AppIntegrantesIdRoute,
  AppEventosIndexRoute: AppEventosIndexRoute,
  AppIntegrantesIndexRoute: AppIntegrantesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RegistroRoute: RegistroRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
